server:
  port: 8444
  ssl:
    enabled: false
    key-alias: localhost
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password
    key-store-type: JKS
    trust-store: /etc/ssl/certs/belgiantrain.jks
    trust-store-password: password
    trust-store-type: JKS


eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8446/eureka}
    should-enforce-registration-at-init: false
    initial-instance-info-replication-interval-seconds: 15