server:
  port: 8444
  ssl:
    enabled: true
    keyStoreType: JKS
    key-alias: selfsigned
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  application:
    name: product

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://azure-dev-belgianrail.be:8446/eureka}