server:
  port: 8444
  ssl:
    enabled: false
    keyStoreType: JKS
    key-alias: selfsigned
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  application:
    name: product

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eureka-server-1.azurewebsites.net/eureka}
  server:
    enableSelfPreservation: true
  instance:
    # If there are two running on the same machine this the second one must have host name 127.0.0.1
    hostname: localhost